import { useEffect, useMemo, useState } from 'react'
import { Activity, Heart, Droplets, Wind, Download, Play, Pause, FlaskConical } from 'lucide-react'
import { LineChart, Line, ResponsiveContainer, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts'

type Scenario = 'rest' | 'exercise' | 'recovery'
const scenarios: Record<Scenario, { name:string; hr:number; rr:number; oxygen:number }> = {
  rest: { name:'Resting baseline', hr:72, rr:15, oxygen:98 },
  exercise: { name:'Exercise response', hr:116, rr:25, oxygen:97 },
  recovery: { name:'Recovery', hr:88, rr:19, oxygen:98 },
}
export default function DemoApp(){
  const [scenario,setScenario]=useState<Scenario>('rest'),[running,setRunning]=useState(true),[tick,setTick]=useState(0),[view,setView]=useState('Overview')
  useEffect(()=>{if(!running)return;const timer=setInterval(()=>setTick(t=>t+1),1000);return()=>clearInterval(timer)},[running])
  const history=useMemo(()=>Array.from({length:60},(_,i)=>{const t=tick-59+i,s=scenarios[scenario];return {second:t,heart_rate:Math.round(s.hr+Math.sin(t*.23)*3),spo2:Number((s.oxygen+Math.sin(t*.09)*.4).toFixed(1)),respiratory_rate:Math.round(s.rr+Math.sin(t*.16)*2)}}),[tick,scenario])
  const latest=history[59]
  const exportCSV=()=>{const csv='source,scenario,second,heart_rate_bpm,spo2_percent,respiratory_rate\n'+history.map(r=>`SIMULATED,${scenario},${r.second},${r.heart_rate},${r.spo2},${r.respiratory_rate}`).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='healthpatch-simulated-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const metrics=[{key:'heart_rate',name:'Heart rate',unit:'bpm',value:latest.heart_rate,icon:Heart,color:'#0d9488'},{key:'spo2',name:'Blood oxygen',unit:'%',value:latest.spo2,icon:Droplets,color:'#3b82f6'},{key:'respiratory_rate',name:'Respiration',unit:'br/min',value:latest.respiratory_rate,icon:Wind,color:'#8b5cf6'}]
  return <div className="min-h-screen bg-[#F5F8FC] text-slate-800">
    <div role="status" className="bg-amber-100 px-5 py-3 text-center text-sm text-amber-950"><strong>PUBLIC INTERACTIVE DEMO</strong> · All readings are simulated. No patient data, accounts, device connection or emergency services.</div>
    <header className="flex flex-wrap items-center justify-between gap-4 border-b bg-white px-6 py-5"><a href="#" className="flex items-center gap-3 text-xl font-bold"><Activity className="text-teal-600"/>HealthPatch <span className="text-xs font-medium text-teal-700">RESEARCH PROTOTYPE</span></a><a className="text-sm text-teal-700" href="https://github.com/24kd1a05c3-dev/healthpatch" target="_blank" rel="noopener noreferrer">View source ↗</a></header>
    <div className="mx-auto flex max-w-7xl flex-col gap-6 p-4 md:flex-row md:p-8"><nav aria-label="Demo views" className="flex gap-2 md:w-48 md:flex-col">{['Overview','Trends','Simulator'].map(v=><button key={v} onClick={()=>setView(v)} aria-current={view===v?'page':undefined} className={`rounded-lg px-4 py-3 text-left text-sm font-medium ${view===v?'bg-teal-700 text-white':'bg-white text-slate-600'}`}>{v}</button>)}</nav>
    <main className="min-w-0 flex-1 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Simulated signal study</p><h1 className="mt-2 text-2xl font-bold">{view==='Simulator'?'Explore a scenario':view==='Trends'?'Signal trends':'Patient command center'}</h1><p className="mt-2 text-sm text-slate-500">Explore monitoring concepts using generated measurements.</p></div><button onClick={exportCSV} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-sm"><Download size={16}/>Export simulated CSV</button></div>
    <section className="flex flex-wrap items-center gap-4 rounded-xl border bg-white p-5"><FlaskConical className="text-teal-600"/><label className="text-sm">Scenario <select aria-label="Simulation scenario" value={scenario} onChange={e=>setScenario(e.target.value as Scenario)} className="ml-3 rounded-md border p-2">{Object.entries(scenarios).map(([key,s])=><option key={key} value={key}>{s.name}</option>)}</select></label><button onClick={()=>setRunning(v=>!v)} className="ml-auto flex items-center gap-2 rounded-md border px-3 py-2 text-sm">{running?<Pause size={16}/>:<Play size={16}/>} {running?'Pause':'Resume'}</button><span className="text-xs text-slate-500">{running?'Generating readings':'Paused'} · {tick}s</span></section>
    <div className="grid gap-4 sm:grid-cols-3">{metrics.map(m=><section key={m.key} className="rounded-xl border bg-white p-5"><m.icon size={22} style={{color:m.color}}/><h2 className="mt-3 text-sm text-slate-500">{m.name}</h2><p className="mt-2 text-3xl font-semibold">{m.value} <small className="text-sm font-normal text-slate-500">{m.unit}</small></p><p className="mt-3 text-xs text-amber-700">SIMULATED MEASUREMENT</p></section>)}</div>
    {(view==='Trends'?metrics:metrics.slice(0,1)).map(m=><section key={m.key} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{m.name} · latest 60 generated samples</h2><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="second" tick={{fontSize:11}}/><YAxis domain={['auto','auto']} tick={{fontSize:11}}/><Tooltip/><Line dataKey={m.key} stroke={m.color} strokeWidth={2} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></section>)}
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{view==='Simulator'?'How this simulation works':'About this demonstration'}</h2><p className="mt-3 text-sm leading-6 text-slate-600">The selected scenario changes the baseline for generated heart rate, oxygen and respiration. Smooth mathematical variation produces the plotted samples. These are invented demonstration values, not measured signals, clinical reference ranges or diagnoses. Pause freezes the stream; exports are marked SIMULATED.</p><p className="mt-3 text-sm leading-6 text-slate-600">The full research project includes FastAPI, MongoDB, authenticated workspaces, replay and statistical observations. Those backend services are not connected to this public demo.</p></section>
    <footer className="py-4 text-xs text-slate-500">HealthPatch · Abhiradh Gorti · Research demonstration, not a medical service.</footer></main></div></div>
}
